### ISSUE TITLE
关于实验的一些问题

### ISSUE THREAD

**Issue by StrategyResin** [XJTU-EEG/LibEER#3]
您好，非常感谢您们提供的 LibEER 框架，它在基于脑电的情感识别研究中的设计与实用性非常优秀，对我的研究帮助很大！在使用该框架进行实验时，我遇到了一些问题，希望能得到您的解答：
1. 我注意到这份工作对应的论文中，对实验结果的表示有一部分是以均值±标准差的形式表示的，例如TABLE 5，我想知道这里的标准差是几次试验进行统计计算得到的？
目前我的做法是在自己搭建的简单模型上进行训练，其中的epoch=300，重复9次并求取九次结果的均值和标准差（在实验中注意到每次300个epoch完成之后会随机划分数据集进行下一组的300个epoch），我想知道我的做法是否是合理的，是否与您论文中的实验设置一致？
![屏幕截图 2024-12-20 160749](https://github.com/user-attachments/assets/ef7b75bb-a73e-4bb3-a4d1-ade67ccd2779)

2. 另一个问题是关于固定随机种子的问题，我注意到您的框架和示例代码里都选择了固定seed来尽量确保可重复性，我想知道如果更换随机种子会有什么影响？
3. 还有一个问题是，在训练过程中（受试者依赖）模型在每次随机划分数据集后，准确率和macro-F1都存在不稳定的现象，请问您认为会是不同受试者之间个体差异过大，导致模型难以泛化导致的吗？
非常感谢您们的贡献与时间，期待您的回复！

**Comment by StrategyResin** [comment]
还有就是，-resume参数并没有实现从检查点文件加载模型的功能

**Comment by XJTU-EEG** [comment]
谢谢您对我们算法库的关注：
1、该表中的标准差是在不同人的数据上进行一次训练测试取得的标准差，在subject-dependent任务下，会对每个人的数据进行独立的实验，将每个人的数据以trail为单位独立划分为训练和测试集，并统计每个人的平均结果和标准差，这个标准差是由任务决定的，例如SEED数据集就会对十五个人每个人单独进行训练测试得到结果。这些在论文当中已经有描述。
2、更换随机数种子会影响需要随机划分情况下的训练测试数据的划分，有可能会影响结果。
3、subject-dependent任务下并不会出现不同受试者之间个体差异过大的问题，因为任务是在同一个人的数据上进行的。不稳定的情况可能还是因为数据量较小，实验学习率，batch等原因造成的。
